=== KITONK/distributed-systems/task3/schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="papers" type="papersType"/>
    <xs:element name="papersType"/>
        <xs:complexType name="papersType">
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element name="paper" type="paperType"/>
            </xs:sequence>
        </xs:complexType>
    <xs:complexType name="paperType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="type" type="xs:string"/>
            <xs:element name="monthly" type="xs:boolean"/>
            <xs:element name="chars" type="charsType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="charsType">
        <xs:sequence>
            <xs:element name="char" type="charType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="charType">
        <xs:sequence>
            <xs:element name="color" type="xs:boolean"/>
            <xs:element name="numberOfPage" type="xs:integer"/>
            <xs:element name="glossy" type="xs:boolean"/>
            <xs:element name="subscriptionIndex" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== KITONK/distributed-systems/task3/Paper.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<papers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation = "schema.xsd">
    <paper>
        <title>t</title>
        <type>t</type>
        <monthly>true</monthly>
        <chars>
            <char>
                <color>true</color>
                <numberOfPage>2</numberOfPage>
                <glossy>true</glossy>
                <subscriptionIndex>123</subscriptionIndex>
            </char>
        </chars>
    </paper>
    <paper>
        <title>e</title>
        <type>e</type>
        <monthly>true</monthly>
        <chars>
            <char>
                <color>true</color>
                <numberOfPage>1</numberOfPage>
                <glossy>false</glossy>
                <subscriptionIndex>1324</subscriptionIndex>
            </char>
        </chars>
    </paper>
</papers>
